name: Deploy
description: Deploys a Python project to PyPI/TestPyPI

inputs:
  pypi-api-token:
    description: API key of PyPI
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

  test-pypi-api-token:
    description: API key of TestPyPI
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: python -m pip install build

    - name: Build distributions
      shell: bash
      run: python -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.test-pypi-api-token }}
        repository-url: https://test.pypi.org/legacy/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-api-token }}
