---
name: Deploy
description: Deploys a Python project to PyPI/TestPyPI

inputs:
  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: python -m pip install build

    - name: Build distributions
      shell: bash
      run: python -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
