---
name: Vale
description: Runs vale over all TeX files in the repo

inputs:
  github-token:
    description: GitHub token
    required: true

  vale-flags:
    description: Flags to pass to vale
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Run Vale
      uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: nofilter
        reporter: github-check
        vale_flags: ${{ inputs.vale-flags }}
