name: Vale
description: Runs vale over all TeX files in the repo

inputs:
  vale-flags:
    description: Flags to pass to vale
    default: ""

runs:
  using: composite
  steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: Run Vale
      uses: errata-ai/vale-action@v2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        fail_on_error: true
        filter_mode: nofilter
        reporter: github-check
        vale_flags: ${{ inputs.vale-flags }}
