---
- description: Default prek hooks for general repos
  entry: ./prek/general/general_hooks.py
  id: general-hooks
  language: script
  name: General hooks
  pass_filenames: false
  require_serial: true
  verbose: true
- description: Default prek hooks for LaTeX repos
  entry: ./prek/latex/latex_hooks.py
  id: latex-hooks
  language: script
  name: LaTeX hooks
  pass_filenames: false
  require_serial: true
  verbose: true
- description: Default prek hooks for Lua repos
  entry: ./prek/lua/lua_hooks.py
  id: lua-hooks
  language: script
  name: Lua hooks
  pass_filenames: false
  require_serial: true
  verbose: true
- description: Default prek hooks for Python repos
  entry: ./prek/python/python_hooks.py
  id: python-hooks
  language: script
  name: Python hooks
  pass_filenames: false
  require_serial: true
  verbose: true
