- id: python-hooks
  name: Python hooks
  description: Default pre-commit hooks for Python repos
  entry: python ./precommit/python/python_hooks.py
  language: python
  require_serial: true
  verbose: true
  additional_dependencies: []
  pass_filenames: false
- id: latex-hooks
  name: LaTeX hooks
  description: Default pre-commit hooks for LaTeX repos
  entry: python ./precommit/latex/latex_hooks.py
  language: python
  require_serial: true
  verbose: true
  pass_filenames: false
