---
- id: general-hooks
  name: General hooks
  description: Default prek hooks for general repos
  entry: prek run --config prek/general-hooks.yaml --all-files
  language: python
  additional_dependencies:
    - prek
  require_serial: true
  verbose: true
- id: latex-hooks
  name: LaTeX hooks
  description: Default prek hooks for LaTeX repos
  entry: prek run --config prek/latex-hooks.yaml --all-files
  language: python
  additional_dependencies:
    - prek
  require_serial: true
  verbose: true
- id: lua-hooks
  name: Lua hooks
  description: Default prek hooks for Lua repos
  entry: prek run --config prek/lua-hooks.yaml --all-files
  language: python
  additional_dependencies:
    - prek
  require_serial: true
  verbose: true
- id: python-hooks
  name: Python hooks
  description: Default prek hooks for Python repos
  entry: prek run --config prek/python-hooks.yaml --all-files
  language: python
  additional_dependencies:
    - prek
  require_serial: true
  verbose: true
