- id: python-hooks
  name: Python hooks
  description: Default pre-commit hooks for Python repos
  entry: ./precommit/run-hooks.py -p python/python-hooks
  language: script
  require_serial: true
  verbose: true
- id: latex-hooks
  name: LaTeX hooks
  description: Default pre-commit hooks for Latex repos
  entry: ./precommit/run-hooks.py -p latex/latex-hooks
  language: script
  require_serial: true
  verbose: true
