- id: python-hooks
  name: Python hooks
  description: Default pre-commit hooks for Python repos
  entry: python-hooks
  language: python
  require_serial: true
  verbose: true
  additional_dependencies: []
- id: latex-hooks
  name: LaTeX hooks
  description: Default pre-commit hooks for LaTeX repos
  entry: latex-hooks
  language: python
  require_serial: true
  verbose: true
  additional_dependencies: []
