# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/settings.yml
---
branches:
  # `default` creates a branch protection rule to against the repo's base branch
  - name: default
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        bypass_pull_request_allowances:
          apps:
            - renovate
          users: []
          teams: []
        dismiss_stale_reviews: true
        dismissal_restrictions: {}
        require_code_owner_reviews: false
        require_last_push_approval: false
        required_approving_review_count: 0
      required_status_checks:
      restrictions:

repository:
  allow_auto_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  has_discussions: false
  has_downloads: false
  has_wiki: false
  squash_merge_commit_message: PR_BODY
  squash_merge_commit_title: PR_TITLE
