---
name: Deploy Website
description: Deploy jekyll website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  ruby-version:
    description: Ruby version
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Find parent directory
      id: find-parent-directory
      shell: bash
      run: >-
        echo parent-directory=$(dirname ${{ env.BUNDLE_GEMFILE }}) >>
        $GITHUB_OUTPUT

    - name: Install and Build
      shell: bash
      working-directory: >-
        ${{ steps.find-parent-directory.outputs.parent-directory }}
      run: >-
        JEKYLL_GITHUB_TOKEN=${{ inputs.github-token }} JEKYLL_ENV=production
        bundle exec jekyll build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: >-
          ${{ steps.find-parent-directory.outputs.parent-directory }}/_site
        publish_branch: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
