---
name: Update Copyright
description: Update the copyright of the licence

inputs:
  github-token:
    description: GitHub token
    required: true

  licence-file:
    description: Path of the licence
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      with:
        fetch-depth: 0

    # yamllint disable-line rule:line-length
    - uses: FantasticFiasco/action-update-license-year@9135da8f9ccc675217e02357c744b6b541d45cb0 # v3
      with:
        path: ${{ inputs.licence-file }}
        token: ${{ inputs.github-token }}

    - name: Merge pull request
      shell: bash
      run: gh pr merge --auto --delete-branch --squash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
