---
name: Update Copyright
description: Update the copyright of the licence

inputs:
  licence-file:
    description: Path of the licence
    required: true

  licence-token:
    description: PAT with public_repo scope.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 0

    # yamllint disable-line rule:line-length
    - uses: FantasticFiasco/action-update-license-year@d837fc83ecb71196807bdf3854208f556e66f6ed # v3
      with:
        path: ${{ inputs.licence-file }}
        token: ${{ inputs.licence-token }}

    - name: Merge pull request
      shell: bash
      run: gh pr merge --auto --delete-branch --squash
      env:
        GITHUB_TOKEN: ${{ inputs.licence-token }}
