---
name: Update Copyright
description: Update the copyright of the licence

inputs:
  licence-file:
    description: Path of the licence
    required: true

  licence-token:
    description: PAT with public_repo scope.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    # yamllint disable-line rule:line-length
    - uses: FantasticFiasco/action-update-license-year@9135da8f9ccc675217e02357c744b6b541d45cb0 # v3
      with:
        path: ${{ inputs.licence-file }}
        token: ${{ inputs.licence-token }}

    - name: Merge pull request
      shell: bash
      run: gh pr merge --auto --delete-branch --squash
      env:
        GITHUB_TOKEN: ${{ inputs.licence-token }}
