---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  requirements-txt:
    description: Path of requirements.txt
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set up Python
      if: inputs.requirements-txt
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: ${{ inputs.requirements-txt }}

    - name: Install dependencies
      if: inputs.requirements-txt
      shell: bash
      run: python -m pip install -r ${{ inputs.requirements-txt }}

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2

    - name: Render ${{ github.ref_name }} branch
      if: github.ref != 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/render@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2

    - name: Publish main branch
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
