---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2

    - name: Render and Publish
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
