---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  requirements-txt:
    description: Path of requirements.txt
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Python
      if: inputs.requirements-txt
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: ${{ inputs.requirements-txt }}

    - name: Install dependencies
      if: inputs.requirements-txt
      shell: bash
      run: python -m pip install -r ${{ inputs.requirements-txt }}

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@87b35bb88b36317fa36b5189e9553b4164a5c5a3 # v2

    - name: Render ${{ github.ref_name }} branch
      if: github.ref != 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/render@87b35bb88b36317fa36b5189e9553b4164a5c5a3 # v2

    - name: Publish main branch
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@87b35bb88b36317fa36b5189e9553b4164a5c5a3 # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
