---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  requirements-txt:
    description: Path of requirements.txt
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Cache Jupyter
      if: inputs.requirements-txt
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .jupyter_cache
        key: quarto-${{ hashFiles('_quarto.yaml') }}

    - name: Set up uv
      if: inputs.requirements-txt
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7
      with:
        activate-environment: true

    - name: Install dependencies
      if: inputs.requirements-txt
      shell: bash
      run: uv pip install -r ${{ inputs.requirements-txt }}

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2

    - name: Render ${{ github.ref_name }} branch
      if: github.ref != 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2

    - name: Publish main branch
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
