---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Python
      if: inputs.pyproject-toml
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      if: inputs.pyproject-toml
      shell: bash
      run: python -m pip install -e .

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@9e48da27e184aa238fcb49f5db75469626d43adb # v2

    - name: Render ${{ github.ref_name }} branch
      if: github.ref != 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/render@9e48da27e184aa238fcb49f5db75469626d43adb # v2

    - name: Publish main branch
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@9e48da27e184aa238fcb49f5db75469626d43adb # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
