---
name: Deploy Quarto
description: Deploy quarto website to GitHub Pages

inputs:
  github-token:
    description: GitHub token
    required: true

  requirements-txt:
    description: Path of requirements.txt
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Cache Jupyter
      if: inputs.requirements-txt
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .jupyter_cache
        key: quarto-${{ hashFiles('_quarto.yaml') }}

    - name: Set up uv
      if: inputs.requirements-txt
      uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa # v7
      with:
        activate-environment: true

    - name: Install dependencies
      if: inputs.requirements-txt
      shell: bash
      run: uv pip install -r ${{ inputs.requirements-txt }}

    - name: Set up Quarto
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/setup@9e48da27e184aa238fcb49f5db75469626d43adb # v2

    - name: Render ${{ github.ref_name }} branch
      if: github.ref != 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/render@9e48da27e184aa238fcb49f5db75469626d43adb # v2

    - name: Publish main branch
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: quarto-dev/quarto-actions/publish@9e48da27e184aa238fcb49f5db75469626d43adb # v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
