---
name: Links
description: Checks the links in a repo work

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - name: Check links
      uses: lycheeverse/lychee-action@v1
      with:
        failIfEmpty: false
        token: ${{ inputs.github-token }}
