---
name: Links
description: Checks the links in a repo work

inputs:
  branch:
    description: GitHub branch to check out
    default: main

  github-token:
    description: GitHub token
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose .

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        ref: ${{ inputs.branch }}

    - name: Check links
      # yamllint disable-line rule:line-length
      uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ inputs.github-token }}
