---
name: Links
description: Checks the links in a repo work

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Check links
      # yamllint disable-line rule:line-length
      uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # v2
      with:
        args: --verbose --no-progress .
        failIfEmpty: false
        token: ${{ inputs.github-token }}
