---
name: Links
description: Checks the links in a repo work

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Check links
      uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1
      with:
        failIfEmpty: false
        token: ${{ inputs.github-token }}
