---
name: Add Issues to Project
description: Add issues to the GitHub project board

inputs:
  projects-token:
    description: PAT with repo and project scopes.
    required: true

  project-url:
    description: URL of the project board to add issues to
    default: https://github.com/users/paddyroddy/projects/1

runs:
  using: composite
  steps:
    - name: Get project data
      # yamllint disable-line rule:line-length
      uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458 # v1.0.1
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ inputs.projects-token }}
