---
name: Documentation
description: Runs pdoc3 on a project and pushes to GitHub Pages

inputs:
  docs-dependency-section:
    description: The location of docs dependencies in pyproject.toml
    required: true

  gh-pages-publish-directory:
    description: The path to publish to GitHub Pages
    required: true

  github-token:
    description: GitHub token
    required: true

  project-directory:
    description: Path to the Python project
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

  template-directory:
    description: Path of the template directory
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: python -m pip install -e ${{ inputs.docs-dependency-section }}

    - name: Create documentation
      shell: bash
      run: >-
        pdoc
        --html ${{ inputs.project-directory }}
        --template-dir ${{ inputs.template-directory}}

    - name: Deploy
      # yamllint disable-line rule:line-length
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.gh-pages-publish-directory }}
        publish_branch: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
