---
name: Documentation
description: Runs pdoc3 on a project and pushes to GitHub Pages

inputs:
  docs-dependency-section:
    description: The location of docs dependencies in pyproject.toml
    required: true

  gh-pages-publish-directory:
    description: The path to publish to GitHub Pages
    required: true

  github-token:
    description: GitHub token
    required: true

  project-directory:
    description: Path to the Python project
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

  template-directory:
    description: Path of the template directory
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: python -m pip install -e ${{ inputs.docs-dependency-section }}

    - name: Create documentation
      shell: bash
      run: >-
        pdoc --html ${{ inputs.project-directory }} --template-dir ${{
        inputs.template-directory}}

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      # yamllint disable-line rule:line-length
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.gh-pages-publish-directory }}
        publish_branch: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
