---
name: Dropbox
description: Upload files to Dropbox

inputs:
  configfile-version:
    description: Dropbox app config version
    required: true

  files-to-upload:
    description: A list of files to upload to dropbox
    required: true

  oauth-app-key:
    description: Dropbox app OAuth key
    required: true

  oauth-app-secret:
    description: Dropbox app OAuth secret
    required: true

  oauth-refresh-token:
    description: Dropbox app OAuth refresh token
    required: true

runs:
  using: composite
  steps:
    - name: Set up Dropbox
      shell: bash
      run: >-
        {
          echo "CONFIGFILE_VERSION=${{ inputs.configfile-version }}";
          echo "OAUTH_APP_KEY=${{ inputs.oauth-app-key }}";
          echo "OAUTH_APP_SECRET=${{ inputs.oauth-app-secret }}";
          echo "OAUTH_REFRESH_TOKEN=${{ inputs.oauth-refresh-token }}";
        } > ~/.dropbox_uploader

    - name: Retrieve Dropbox uploader script
      shell: bash
      run: >-
        curl
        https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh
        -o dropbox_uploader.sh;
        chmod +x dropbox_uploader.sh

    - name: Upload PDF
      shell: bash
      run: >-
        for file in ${{ inputs.files-to-upload }}; do
        echo $file;
        ./dropbox_uploader.sh upload $file $file;
        done
