name: Dropbox
description: Upload files to Dropbox

inputs:
  configfile-version:
    description: Dropbox app config version
    required: true

  files-to-upload:
    description: A list of files to upload to dropbox
    required: true

  oauth-app-key:
    description: Dropbox app OAuth key
    required: true

  oauth-app-secret:
    description: Dropbox app OAuth secret
    required: true

  oauth-refresh-token:
    description: Dropbox app OAuth refresh token
    required: true

runs:
  using: composite
  steps:
    - name: checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up Dropbox
      shell: bash
      run: |-
        echo "CONFIGFILE_VERSION=$CONFIGFILE_VERSION" > ~/.dropbox_uploader
        echo "OAUTH_APP_KEY=$OAUTH_APP_KEY" >> ~/.dropbox_uploader
        echo "OAUTH_APP_SECRET=$OAUTH_APP_SECRET" >> ~/.dropbox_uploader
        echo "OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN" >> ~/.dropbox_uploader
      env:
        CONFIGFILE_VERSION: ${{inputs.configfile-version }}
        OAUTH_APP_KEY: ${{ inputs.oauth-app-key }}
        OAUTH_APP_SECRET: ${{ inputs.oauth-app-secret }}
        OAUTH_REFRESH_TOKEN: ${{ inputs.oauth-refresh-token }}

    - name: Retrieve Dropbox uploader script
      shell: bash
      run: |-
        curl "https://raw.githubusercontent.com/andreafabrizi/\
        Dropbox-Uploader/master/dropbox_uploader.sh" \
        -o dropbox_uploader.sh
        chmod +x dropbox_uploader.sh

    - name: Upload PDF
      shell: bash
      run: |-
        for file in ${{ inputs.files-to-upload }}; do \
        echo $file; \
        ./dropbox_uploader.sh upload $file $file; \
        done
