---
name: Test
description: Runs tox on the repo

inputs:
  cache-path:
    description: Paths to cache
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Cache tox/pooch
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ inputs.cache-path }}
        key: test-${{ hashFiles('pyproject.toml') }}

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: >-
        python -m pip install tox tox-gh

    - name: Test with tox
      shell: bash
      run: tox run
      env:
        TOX_GH_MAJOR_MINOR: ${{ inputs.python-version }}
