---
name: Test
description: Runs tox on the repo

inputs:
  cache-path:
    description: Paths to cache
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Cache ${{ inputs.cache-path }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ inputs.cache-path }}
        key: test-${{ hashFiles('pyproject.toml') }}

    - name: Set up uv ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa # v7
      with:
        activate-environment: true
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv pip install tox tox-gh

    - name: Test with tox
      shell: bash
      run: uv tox run
      env:
        TOX_GH_MAJOR_MINOR: ${{ inputs.python-version }}
