---
name: Test
description: Runs tox on the repo

inputs:
  cache-path:
    description: Paths to cache
    required: true

  operating-system:
    description: Operating system to test
    required: true

  pyproject-toml:
    description: Path of pyproject.toml
    required: true

  python-version:
    description: Version of python to test
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Cache tox/pooch
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ${{ inputs.cache-path }}
        key: test-${{ hashFiles('pyproject.toml') }}

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pyproject-toml }}

    - name: Install dependencies
      shell: bash
      run: >-
        python -m pip install tox tox-gh-actions

    - name: Test with tox
      shell: bash
      run: tox run
      env:
        OS: ${{ inputs.operating-system }}
