name: ChkTeX
description: Runs ChkTeX over all TeX files in the repo

runs:
  using: composite
  steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: Run chktex
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |-
          for file in *.tex; do \
          echo $file; \
          chktex $file | tee /dev/stderr | (! grep -q ^); \
          done
