---
name: ChkTeX
description: Runs ChkTeX over all TeX files in the repo

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Run chktex
      # yamllint disable-line rule:line-length
      uses: xu-cheng/texlive-action@475ab07999e9709e524c3708488c8c170d3a6611 # v3
      with:
        scheme: full
        run: >-
          for file in *.tex; do echo $file; chktex $file | tee /dev/stderr | (!
          grep -q ^); done
