---
name: Compile LaTeX
description: Runs latexmk on the repo

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Build PDF
      # yamllint disable-line rule:line-length
      uses: xu-cheng/texlive-action@f886de8159e5952a131848a5fa9c3196a2132b5d # v2
      with:
        scheme: full
        run: latexmk -quiet
