---
name: Compile LaTeX
description: Runs latexmk on the repo

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Build PDF
      # yamllint disable-line rule:line-length
      uses: xu-cheng/texlive-action@f886de8159e5952a131848a5fa9c3196a2132b5d # v2
      with:
        scheme: full
        run: latexmk -quiet
