---
name: Compile LaTeX
description: Runs latexmk on the repo

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Build PDF
      # yamllint disable-line rule:line-length
      uses: xu-cheng/texlive-action@475ab07999e9709e524c3708488c8c170d3a6611 # v3
      with:
        scheme: full
        run: latexmk -quiet
