name: Deploy Website
description: Deploy jekyll website to GitHub Actions

inputs:
  docs-directory:
    description: Directory of the documentation Gemfile
    default: .

  github-token:
    description: GitHub token
    required: true

  ruby-version:
    description: Ruby version
    required: true

runs:
  using: composite
  steps:
    - name: checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Find parent directory
      id: find-parent-directory
      shell: bash
      run: >-
        echo parent-directory=$(dirname ${{ env.BUNDLE_GEMFILE }})
        >> $GITHUB_OUTPUT

    - run: echo ${{ steps.find-parent-directory.output.parent-directory }}
      shell: bash

    - name: Install and Build
      shell: bash
      working-directory: $(dirname ${{ env.BUNDLE_GEMFILE }})
      run: >-
        JEKYLL_GITHUB_TOKEN=${{ inputs.github-token }}
        JEKYLL_ENV=production
        bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ env.BUNDLE_GEMFILE }}/../_site
        publish_branch: gh-pages
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
