---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}

      - uses: ./actions/add-to-project
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_PAT }}
        with:
          project-token: ${{ env.PROJECT_TOKEN }}
