name: Update Copyright

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/licence
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./README.md
