---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}

      - uses: ./actions/links
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
