---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}

      - uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      - uses: ./actions/vale
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
