---
name: Bump Version Tag

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
      - "!**/*.json5"
      - "!**/*.md"
      - "!**/*.txt"
      - "!.github/**"
      - "!.gitignore"
      - "!.pre-commit-config.yaml"
      - "!pyproject.toml"
  workflow_dispatch:

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump-version
        # yamllint disable-line rule:line-length
        uses: anothrNick/github-tag-action@afe4b67b57b8ab0908e4767109a5342003639e2e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Extract major tag
        id: extract-major
        run: >-
          echo major_tag=$(echo ${{ steps.bump-version.outputs.new_tag }} | cut
          -d'.' -f1) >> $GITHUB_OUTPUT

      # this is done manually as need a non-annotated tag
      # TODO: replace with https://github.com/actions/publish-action
      - name: Update major tag
        run: >-
          git config user.name github-actions; git config user.email
          github-actions@github.com; git tag --force ${{
          steps.extract-major.outputs.major_tag }} ${{
          steps.bump-version.outputs.new_tag }}; git push origin ${{
          steps.extract-major.outputs.major_tag }} --force
