name: Bump Version Tag

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
      - "!.github/**"
      - "!.gitignore"
      - "!.pre-commit-config.yaml"
      - "!**/*.json"
      - "!**/*.md"
      - "!pyproject.toml"

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Get new tag version
        id: bump-version
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # 1.67.0
        env:
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Update major tag
        uses: rickstaa/action-update-semver@f1596c59134ba100443e47894de60f76d97950c7 # v1
        with:
          major_version_tag_only: true
          tag: ${{ steps.bump-version.outputs.new_tag }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # 1.67.0
        env:
          CUSTOM_TAG: ${{ steps.bump-version.outputs.new_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
