name: Bump Version Tag

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
      - "!.github/**"
      - "!.gitignore"
      - "!.pre-commit-config.yaml"
      - "!**/*.json"
      - "!**/*.md"
      - "!pyproject.toml"

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # 1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Update major tag
        uses: nowactions/update-majorver@v1
